// Category Constant Types
export const FETCH_CATEGORY_REQUEST='FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS='FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILOUR='FETCH_CATEGORY_FAILOUR';

export const SET_CURRENT_CATEGORY='SET_CURRENT_CATEGORY';

// Products Constant Types
export const FETCH_PRODUCT_REQUEST='FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS='FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILOUR='FETCH_PRODUCT_FAILOUR';


//Cart Canstant Types
export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const INCREASE_QUANTITY_OF_PRODUCT='INCREASE_QUANTITY_OF_PRODUCT';
export const DECREASE_QUANTITY_OF_PRODUCT='DECREASE_QUANTITY_OF_PRODUCT';